### PR TITLE
Fix infer signature

### PR DESCRIPTION
**Pull request by vishniakov-nikolai**
### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

### CODE REVIEW

**Comment by vishniakov-nikolai** [comment]
@almilosz I need your help here. 
- Common API implementation in node package need to be updated
- Eslint warnings need to be fixed for code in **./samples/node** directory

**Comment by almilosz** [comment]
Node package infer() method has to be overloaded to support the following parameter lists:
```
infer(tensor: ITensor): Promise<ITensor>;
infer(dataArray: number[], shape: IShape | number[]): Promise<ITensor>;
```

**Review by almilosz — CHANGES_REQUESTED** [review]
Please review and merge eslint refactor from PR#12 before this one.
Beside that looks good to me.

**Review by almilosz — APPROVED** [review]
LGTM

**Pull request merged**
